language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  # Python 2.7 has very old pip by default that doesn't have tensorflow.
  - pip install --upgrade pip
  - pip install numpy tensorflow
# command to run tests
script: "nosetests  --logging-level=WARNING"