dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  matrix:
    - TF_VERSION=1.13.2
    - TF_VERSION=1.15
    - TF_VERSION=2.0
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install tensorflow==$TF_VERSION
  - pip install coveralls
# command to run tests
script:
  nosetests  --logging-level=WARNING --with-coverage --cover-package=t3f
after_success:
  coveralls
