dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  matrix:
    - TF_VERSION=1.3
    - TF_VERSION=1.4
    - TF_VERSION=1.5
    - TF_VERSION=1.10
    - TF_VERSION=1.11
# command to install dependencies
install:
  # Python 2.7 has very old pip by default that doesn't have tensorflow.
  - pip install numpy tensorflow==$TF_VERSION keras
  - pip install coveralls
# command to run tests
script:
  nosetests  --logging-level=WARNING --with-coverage --cover-package=t3f
after_success:
  coveralls
